name: Build Separated EXEs
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install MinGW
        run: sudo apt-get install -y mingw-w64
      - name: Build Both EXEs
        run: |
          x86_64-w64-mingw32-gcc virtual_os.c -o virtual_os.exe
          x86_64-w64-mingw32-gcc tools_bang.c -o tools_bang.exe
      - name: Archive Production Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Bang-OS-Release
          path: |
            virtual_os.exe
            tools_bang.exe
